version: "3.2"

services: 
  postgres:
    container_name: postgres-ilumeo
    image: postgres
    environment: 
      POSTGRES_USER: ilumeo
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ilumeoDB
    volumes:
      - ./data:/data/postgres
    ports:
      - ${DB_PORT}:${DB_PORT}

  pontoilumeoapi:
    image: node:latest
    container_name: ilumeo-api
    restart: always
    depends_on:
      - postgres
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"