version: "3"

services: 
  postgres:
    image: 'postgres:latest'
    container_name: postgres-ilumeo
    restart: always
    environment: 
      POSTGRES_USER: ilumeo
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ilumeoDB
    volumes:
      - ./data:/data/postgressql/data
    ports:
      - "5432:5432"